// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0FyR39Gg_lGx6r0BAfNKun07Jrcv9vjA',
    appId: '1:148513483411:web:dcfbae4b9e44a4e802fb66',
    messagingSenderId: '148513483411',
    projectId: 'app-reporte-infraestructura',
    authDomain: 'app-reporte-infraestructura.firebaseapp.com',
    storageBucket: 'app-reporte-infraestructura.appspot.com',
    measurementId: 'G-N63DWM9W9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgCZOAv5OsWbf-FKJaYkCOXvY4KL3sgC0',
    appId: '1:148513483411:android:7aadd101aa2a3b9e02fb66',
    messagingSenderId: '148513483411',
    projectId: 'app-reporte-infraestructura',
    storageBucket: 'app-reporte-infraestructura.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkmqFaD8CkmHeV0R74lrORDM73IobO9I',
    appId: '1:148513483411:ios:f20b6077587af30802fb66',
    messagingSenderId: '148513483411',
    projectId: 'app-reporte-infraestructura',
    storageBucket: 'app-reporte-infraestructura.appspot.com',
    iosBundleId: 'com.example.appReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhkmqFaD8CkmHeV0R74lrORDM73IobO9I',
    appId: '1:148513483411:ios:f20b6077587af30802fb66',
    messagingSenderId: '148513483411',
    projectId: 'app-reporte-infraestructura',
    storageBucket: 'app-reporte-infraestructura.appspot.com',
    iosBundleId: 'com.example.appReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0FyR39Gg_lGx6r0BAfNKun07Jrcv9vjA',
    appId: '1:148513483411:web:c8fe0d3651562afd02fb66',
    messagingSenderId: '148513483411',
    projectId: 'app-reporte-infraestructura',
    authDomain: 'app-reporte-infraestructura.firebaseapp.com',
    storageBucket: 'app-reporte-infraestructura.appspot.com',
    measurementId: 'G-9N4D4GQSWG',
  );

}